### GENERAL SETTINGS ###

# Site settings
title: EuroSoc.
description: "We are a European society at York University."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://York-EuroSoc.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url: http://facebook.com/YorkEuroSoc/
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Some Ave, 987,
    - 23890, New York,
    - United States.
email: eurosoc@yusu.ac.uk
tel:


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Freddy Van Randwyck
    position: President & Founder
    text: Provides leadership for the Society. Ensures the Society adheres to all the YUSU regulations and is in contact with YUSU.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: facebook
        url: http://facebook.com/freddy.vanrandwyck
  - name: Will Wood
    position: Vice President / Secretary
    text: Takes care of the admin the Society's website. Arranges the meetings and organizes the venues.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: facebook
        url: http://facebook.com/will6767
  - name: Hermione Elderton
    position: Welfare, Liberation and Media Management Officer
    text: In charge of the social media pages and events (Facebook & Twitter). Deals with equality/ liberation issues from international students. Maintains contact with exchange students and help integrate them into the society and events. Acts as a bridge between YUSU Door Safe and the society to provide safety and welfare for students at events.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:he618@york.ac.uk
      - title: facebook
        url: http://facebook.com/hermione.elderton
  - name: Hugo Tamassi
    position: Treasurer
    text: In charge of all the finance and laws for the society. Organizing any fundraising and sponsorship for the society.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:ht851@york.ac.uk
      - title: facebook
        url: http://facebook.com/hugo.tomassi.9

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "EuroSoc was setup to help represent the minor European nations. We want to provide a platform to help integrate European culture into our life at York."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
